[package]
name = "rproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
include_dir = "0.7.3"
maxminddb = "0.23.0"
reqwest = { version = "0.11.17", features = ["blocking"] }
tokio = { version = "1.28.0", features = ["rt-multi-thread", "macros"] }
trust-dns-resolver = "0.22.0"
