name: Generate changelog
on:
  push

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: BobAnkh/auto-generate-changelog@v1.2.4
      with:
        REPO_NAME: 'zevtyardt/rust-proxybroker'
        ACCESS_TOKEN: ${{secrets.TOKEN}}
        PATH: 'CHANGELOG.md'
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat:Feature,chore:Code maintenance,fix:Bug Fixes,docs:Documentation,refactor:Refactor,perf:Performance Improvements,test:Testing'
